# Create WAF Regional Web ACL with Rate-Based Rule to Prevent HTTP Flood DDoS Attack
WAFRegionalWebACL:
  Type: AWS::WAFv2::WebACL
  Properties:
    Name: APIGateway-Block-DoS-DoW
    Scope: REGIONAL  # Regionale Web ACL
    Description: WAF Regional Web ACL zum Blockieren von DoS- und DoW-Angriffen
    DefaultAction: 
      Block: {} # Standard-Aktion bei Regeltreffer: Anfragen blocken
    VisibilityConfig:
      SampledRequestsEnabled: true
      CloudWatchMetricsEnabled: true
      MetricName: ApiGateway-Block-DoS-DoW-Metric
    Rules:
      - Name: Block-DoS-DoW-Rule  # Name der Regel
        Priority: 0  # Priorit채t der Regel (niedrige Priorit채t wird zuerst ausgewertet)
        Action:
          Block: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: Block-DoS-DoW-Rule-Metric
        Statement:
          RateBasedStatement: 
            AggregateKeyType: IP  # IP-Adresse als Grundlage f체r die Ratenbeschr채nkung
            Limit: 150  # Maximale Anfragen pro IP in einem Zeitraum
            EvaluationWindowSec: 60  # Zeitraum in Sekunden