# WAF Web ACL mit ratenbasierter Regel zur Prävention von DoS/DDoS- und DoW-Angriffen
WAFRegionalWebACL:
  Type: AWS::WAFv2::WebACL
  Properties:
    Name: APIGateway-Block-DoS-DoW
    Scope: REGIONAL
    Description: WAF Regional Web ACL zum Blockieren von DoS- und DoW-Angriffen
    DefaultAction: 
      Block: {} # Standard-Aktion bei Regeltreffer: Anfragen blocken
    VisibilityConfig:
      SampledRequestsEnabled: true
      CloudWatchMetricsEnabled: true
      MetricName: ApiGateway-Block-DoS-DoW-Metric
    Rules:
      - Name: Block-DoS-DoW-Rule
        Priority: 0  # Priorität der Regel (niedrige Priorität wird zuerst ausgewertet)
        Action:
          Block: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: Block-DoS-DoW-Rule-Metric
        Statement:
          RateBasedStatement: 
            AggregateKeyType: IP  # IP-Adresse als Grundlage für die Ratenbeschränkung
            Limit: 150  # Maximale Anfragen pro IP in einem Zeitraum
            EvaluationWindowSec: 60  # Zeitraum in Sekunden